ALTER TABLE llx_lmdbrexelpunchout_session_line ADD INDEX idx_lmdbrexelpunchout_line_entity (entity);
ALTER TABLE llx_lmdbrexelpunchout_session_line ADD INDEX idx_lmdbrexelpunchout_line_session (fk_session);
ALTER TABLE llx_lmdbrexelpunchout_session_line ADD INDEX idx_lmdbrexelpunchout_line_vendor_ref (entity, vendor_ref);
ALTER TABLE llx_lmdbrexelpunchout_session_line ADD INDEX idx_lmdbrexelpunchout_line_product (fk_product);
ALTER TABLE llx_lmdbrexelpunchout_session_line ADD INDEX idx_lmdbrexelpunchout_line_supplier_price (fk_product_fournisseur_price);
ALTER TABLE llx_lmdbrexelpunchout_session_line ADD INDEX idx_lmdbrexelpunchout_line_orderdet (fk_commandefourndet);
